// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1uKvb_MbVQ0G_9t0NfPdTnkcC7XZIhVE',
    appId: '1:696308061060:web:e4f9f9dd608c64654fc3d1',
    messagingSenderId: '696308061060',
    projectId: 'flutterapp-fcc0e',
    authDomain: 'flutterapp-fcc0e.firebaseapp.com',
    storageBucket: 'flutterapp-fcc0e.appspot.com',
    measurementId: 'G-YXFJE4MR0W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhWZGEHvr2XylzHLSn_ERwpHP62w55290',
    appId: '1:696308061060:android:6ab490b47f4c1dcb4fc3d1',
    messagingSenderId: '696308061060',
    projectId: 'flutterapp-fcc0e',
    storageBucket: 'flutterapp-fcc0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDslf3_3oQUTa12doivkj1KDgJOqmuWV8k',
    appId: '1:696308061060:ios:6d69f27283634ca54fc3d1',
    messagingSenderId: '696308061060',
    projectId: 'flutterapp-fcc0e',
    storageBucket: 'flutterapp-fcc0e.appspot.com',
    iosClientId: '696308061060-lup4r7ll3frobqbhv3ftm8ccum0efahi.apps.googleusercontent.com',
    iosBundleId: 'com.example.snakegame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDslf3_3oQUTa12doivkj1KDgJOqmuWV8k',
    appId: '1:696308061060:ios:6d69f27283634ca54fc3d1',
    messagingSenderId: '696308061060',
    projectId: 'flutterapp-fcc0e',
    storageBucket: 'flutterapp-fcc0e.appspot.com',
    iosClientId: '696308061060-lup4r7ll3frobqbhv3ftm8ccum0efahi.apps.googleusercontent.com',
    iosBundleId: 'com.example.snakegame',
  );
}
